### ISSUE TITLE
Didnt work. Also, what if you have 2 folders such as containers and components

### ISSUE THREAD

**Issue by corganfuzz** [CVarisco/delete-react-zombies#1]
Using create-react-app

package.json:

```
    "npm": "^5.7.1",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-graph-vis": "^1.0.2",
    "react-leaflet": "^1.7.1",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^1.0.13",
    "react-table": "^6.8.0",
    "react-tap-event-plugin": "^2.0.1"
```

Some components are on my  **containers** folder and the other ones are in the **components** folder
Also, please change the README and include the --path option. It's not there but it is in the GIF

**Comment by Daidalos117** [comment]
It seems it doesn't work with normal JS files? I actually never seen someone using .jsx in React project..

**Comment by k1ker** [comment]
Same. I have many unused components, but is gives me: "Unused components not found!"

**Comment by CVarisco** [comment]
Hi Guys!
thanks a lot for your feedback!

Could you share with me more information to understand what's going on?

**Comment by chrisbodhi** [comment]
I believe I experienced the same issue -- based on the information in the README, this utility is looking for files with the `.jsx` file extension. However, all of the components in my project are using `.js`. Since there are no files end with `.jsx`, the utility returns the message that no unused components are found.

As a suggestion, being able to specify the file extension used for a project's React components would be useful!

**Comment by JeffersonFilho** [comment]
https://github.com/CVarisco/delete-react-zombies/pull/3 This should fix this issue! You can define the file extension you want to search for. 

Example: `--extension js` `--extension ts`

Default is: `jsx`

**Comment by CVarisco** [comment]
Thank you guys for your contribution!
I'll merge and publish a new version ASAP.

PS: I'm working in a new version of the library 😀

**Comment by CVarisco** [comment]
Thanks to @JeffersonFilho now you can choose the extension!

**Comment by JeffersonFilho** [comment]
No worries!

**Comment by CVarisco** [comment]
Closed because a new version is published!
