### ISSUE TITLE
cli parameter to delete all unused files

### ISSUE THREAD

**Issue by RishabhTayal** [CVarisco/delete-react-zombies#2]
Is there a parameter that we can pass to bypass the confirmation when an unused file is found and delete them automatically?

**Comment by CVarisco** [comment]
Could be a good option!

I'm working to the v2 fo the library and I'll add `--force` to delete all the files bypassing the confirmation

**Comment by CVarisco** [comment]
@RishabhTayal the v2 is out now with the `--force` argument!
