### ISSUE TITLE
Support absolut import by using baseUrl

### ISSUE THREAD

**Issue by mxschmitt** [CVarisco/delete-react-zombies#9]
It would be cool, if this tool could also support absolut imports by using the baseUrl option in a jsconfig.

```
{
  "compilerOptions": {
    "baseUrl": "app"
  }
}

```

**Comment by CVarisco** [comment]
Hi @mxschmitt,

thanks for your help! 
I'll take it when I'll be free, but if you want you can contribute 👍

**Comment by mxschmitt** [comment]
> Hi @mxschmitt,
> 
> thanks for your help!
> I'll take it when I'll be free, but if you want you can contribute 👍

Hey,
I would create a PR to integrate this feature if you want. I guess in this week, I keep you updated.
Best regards
Max
